# Generated by Django 5.0.6 on 2024-08-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="users",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="noticias", to="main.user"
            ),
        ),
    ]
