# Generated by Django 5.0.6 on 2024-08-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_noticia_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="cuerpo",
            field=models.TextField(default=""),
        ),
    ]
